spring:
  application:
    name: goos-jms
  artemis:
    mode: embedded
    embedded:
      enabled: true
      persistent: false

messaging:
  auction:
    queue: queue-auction-house
  sniper:
    queue: queue-sniper

logging:
  level:
    org.apache.activemq.audit: OFF
